
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Lifting"
version = "2025.3.0"
description = "Wavelet based lifting scheme to compress irregular images over multi-dimensional data"
readme = "README.md"
maintainers = [{name = "Shruti Nath", email = "shruti@probabl.ai"}]
dependencies = ["numpy>=1.15","numpy<2","regionmask", "pygam"]
requires-python = ">=3.7"

[project.urls]
repository = "https://github.com/snath-xoc/Lifting.git"

download = "https://test.pypi.org/project/Lifting/2025.3.0/"

tracker = "https://github.com/snath-xoc/Lifting/issues"

[tool.black]
    py36 = true
    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist

      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
    )/'''
